#!/bin/bash


## name
declare -a "_ga_arg1_test"


## variable
_gs_mode_test="true"

_ga_arg1_bwrapsh=(
        --overlay-src "$(pwd)"
        --tmp-overlay "$(pwd)"
        --chdir "$(pwd)"
        "${_ga_arg1_test[@]}"
)

