#!/bin/bash


## name
declare -a "_ga_arg1_bwrapsh_test"


## variable
_gs_mode_test="true"

_ga_arg1_bwrapsh=(
        --bind "$(pwd)"{,}
        --ro-bind-try "$(pwd)/.git"{,}
        --overlay-src "/usr/share/bwrapsh/main/patch/bash"
        --tmp-overlay "${HOME}"
        --chdir "$(pwd)"
        "${_ga_arg1_bwrapsh_test[@]}"
)

