#!/bin/bash


## name
declare -a "_ga_arg1_bwrapsh_test"


## variable
_gs_mode_test="true"
_gs_mode_network="true"

_ga_arg1_bwrapsh=(
        --bind "$(pwd)"{,}
        --ro-bind-try "$(pwd)/.git"{,}
        --chdir "$(pwd)"
        "${_ga_arg1_bwrapsh_test[@]}"
)

