#!/bin/bash


## name
declare -a "_ga_arg1_bwrapsh_test"


## variable
_gs_mode_test="true"

_ga_arg1_bwrapsh=(
        --ro-bind "$(pwd)"{,}
        --chdir "$(pwd)"
        "${_ga_arg1_bwrapsh_test[@]}"
)

