#!/bin/bash


## name
declare -a "_ga_arg1_bwrapsh_test"


## load
'_gF_tool_load' "profile"


## variable
_gs_mode_test="true"

_ga_arg1_bwrapsh=(
        --bind "$(pwd)"{,}
        --ro-bind-try "$(pwd)/.git"{,}
        --chdir "$(pwd)"
        "${_ga_arg1_bwrapsh_test[@]}"
)

