#!/bin/bash


## name
declare -ga "_ga_exec_sparkle"


## load
function _ef_load_profile () {
        _ga_arg1_bwrapsh_codium=(
                --chdir "${HOME}/.config/VSCodium/User"
        )
}
declare -fx "_ef_load_profile"


## array
_ga_exec_codium=(
        '/usr/bin/bwrapsh'
        dbusproxy
        "codium"
        "${@}"
)


## execute
"${_ga_exec_codium[@]}"

