#!/bin/bash



### init
## name
declare -x "XDG_RUNTIME_DIR"
declare "_gs_init_name"
declare "_gs_init_exec"
declare "_gs_mode_profile"
declare "_gs_mode_dbusproxy"
declare "_gs_mode_network"
declare "_gs_mode_test"
declare "_gs_dirs_profile"
declare "_gs_path_profile"
declare "_gs_dirs_dbusproxy"
declare "_gs_path_dbusproxy"
declare "_gs_stps_dbusproxy"
declare -i "_gi_stat_ss"
declare -i "_gi_proc_dbusproxy"
declare -i "_gi_loop"
declare -a "_ga_exec_dbusproxy"
declare -a "_ga_arg1_dbusproxy"
declare -a "_ga_exec_bwrapsh"
declare -a "_ga_arg1_bwrapsh"
declare -a "_ga_arg2_bwrapsh"
declare -a "_ga_bwrapsh_dbusproxy"
declare -a "_ga_bwrapsh_dbusproxy_true"
declare -a "_ga_bwrapsh_network"
declare -f "_gf_tool_echo"
declare -f "_gf_tool_stps"
declare -f "_ef_load_init"
declare -f "_ef_load_dbusproxy"
declare -f "_ef_load_bwrapsh"


## function
function _gf_tool_echo () 
{
        declare -a "_la_exec_notifysend" ;
        #       #
        echo -e "\n${4}\033[${1:?}${2:?}: ${3:?}\033[0m" ;
        #       #
        _la_exec_notifysend=(
                '/usr/bin/notify-send'
                "${2}"
                "${3}"
        )
        #       #
        "${_la_exec_notifysend[@]}" ;
}

function _gf_tool_stps () 
{
        declare "_ls_stps"="${?}:${!}" ;
        declare -i "_li_stat"="${_ls_stps%%:*}" ;
        declare -i "_li_ppid"="${_ls_stps##*:}" ;
        #       #
        declare -i "_li_proc" ;
        declare -a "_la_exec_pgrep" ;
        #       #
        if [[ "${_li_stat}" != "0" ]] ; then
                exit "${_li_stat}" ;
        fi
        #       #
        _la_exec_pgrep=(
                '/usr/bin/pgrep'
                -P "${_li_ppid}"
                -x "${2:?}"
        )
        #       #
        _li_proc="$("${_la_exec_pgrep[@]}")" ;
        #       #
        declare -g "_gi_proc_${1:?}"="${_li_proc}" ;
}


## initialation
if [[ -z "${_gs_init_name}" ]] ; then
        _gs_init_name="${1:?}" || exit
fi


## profile
_gs_dirs_profile="/_and/config/bwrapsh/profile"
_gs_path_profile="${_gs_dirs_profile}/${_gs_init_name}"

if [[ -z "${_gs_mode_profile}" ]] ; then
        _gs_mode_profile="true"
fi

if [[ "${_gs_mode_profile}" == "true" && -r "${_gs_path_profile}" ]] ; then
        source "${_gs_path_profile}"
fi


## load
declare -F "_ef_load_init"

if [[ "${?}" == "0" ]] ; then
        '_ef_load_init'
fi


## environment
if [[ -e "${XDG_RUNTIME_DIR}" ]] ; then
        XDG_RUNTIME_DIR="/run/user/$('/usr/bin/id' -u)"
fi



### dbusproxy
## load
declare -F "_ef_load_dbusproxy"

if [[ "${?}" == "0" ]] ; then
        '_ef_load_dbusproxy'
fi


## mode
if [[ -z "${_gs_mode_dbusproxy}" ]] ; then
        _gs_mode_dbusproxy="true"
fi


## variable
_gs_dirs_dbusproxy="${XDG_RUNTIME_DIR}/_bwrapsh/dbusproxy"
_gs_path_dbusproxy="${_gs_dirs_dbusproxy}/${_gs_init_name}"


## check
if [[ "${_gs_mode_dbusproxy}" == "true" ]] ; then
        '/usr/bin/ss' -a | grep "${_gs_path_dbusproxy}"
else
        false
fi

_gi_stat_ss="${?}"

if [[ "${_gi_stat_ss}" == "0" ]] ; then
        '_gf_tool_echo' "33m" "WARNING" "The program is running."
        exit "1"
fi


## array
_ga_exec_dbusproxy=(
        '/usr/bin/xdg-dbus-proxy'
        ${DBUS_SESSION_BUS_ADDRESS}
        "${_gs_path_dbusproxy}"
        --filter
        --talk="org.freedesktop.Notifications"
        --talk="org.kde.StatusNotifierWatcher"
        "${_ga_arg1_dbusproxy[@]}"
)

_ga_bwrapsh_dbusproxy_true=(
        --ro-bind "${_gs_path_dbusproxy}" "${XDG_RUNTIME_DIR}/bus"
        --setenv "DBUS_SESSION_BUS_ADDRESS" "unix:path=${XDG_RUNTIME_DIR}/bus"
)


## execute
if [[ "${_gs_mode_dbusproxy}" == "true" ]] ; then
        _ga_bwrapsh_dbusproxy=("${_ga_bwrapsh_dbusproxy_true[@]}")
        #       #
        '/usr/bin/mkdir' -pv "${_gs_dirs_dbusproxy}" || exit
        #       #
        (
        "${_ga_exec_dbusproxy[@]}"
        exit ) &
else
        true
fi


## watch
'_gf_tool_stps' "dbusproxy" "xdg-dbus-proxy"


## wait
for _gi_loop in {1..100} ; do
        if [[ "${_gs_mode_dbusproxy}" != "true" ]] ; then
                break
        fi
        #       #
        '/usr/bin/ss' -a | grep "${_gs_path_dbusproxy}"
        #       #
        _gi_stat_ss="${?}"
        #       #
        if [[ "${_gi_stat_ss}" == "0" ]] ; then
                break
        elif [[ "${_gi_loop}" -lt "10" ]] ; then
                '/usr/bin/sleep' "0.5s"
        else
                exit "1"
        fi
done



### bwrap
## load
declare -F "_ef_load_bwrapsh"

if [[ "${?}" == "0" ]] ; then
        '_ef_load_bwrapsh'
fi


## mode
if [[ "${_gs_mode_network}" == "true" ]] ; then
        _ga_bwrapsh_network=(--share-net)
else
        _ga_bwrapsh_network=(--unshare-net)
fi

if [[ "${_gs_mode_test}" == "true" ]] ; then
        _gs_init_exec="/bin/bash"
elif [[ -z "${_gs_init_exec}" ]] ; then
        _gs_init_exec="${2:?}" || exit
fi

if [[ "${_gs_init_exec}" == "_null" ]] ; then
        _gs_init_exec="/bin/sh"
fi


## argument
shift 1
shift 1


## array
_ga_exec_bwrapsh=(
        '/usr/bin/bwrap'
        --unshare-all
        --die-with-parent
        --proc "/proc"
        --dev "/dev"
        --tmpfs "/tmp"
        --tmpfs "${XDG_RUNTIME_DIR}"
        --tmpfs "${HOME}"
        --ro-bind "/etc" "/etc"
        --ro-bind "/srv" "/srv"
        --ro-bind "/opt" "/opt"
        --ro-bind "/usr/bin" "/usr/bin"
        --ro-bind "/usr/include" "/usr/include"
        --ro-bind "/usr/lib" "/usr/lib"
        --ro-bind "/usr/lib64" "/usr/lib64"
        --ro-bind "/usr/libexec" "/usr/libexec"
        --ro-bind "/usr/share" "/usr/share"
        --ro-bind "/usr/src" "/usr/src"
        --symlink "/usr/bin" "/bin"
        --symlink "/usr/lib" "/lib"
        --symlink "/usr/lib64" "/lib64"
        --dev-bind "/dev/dri" "/dev/dri"
        --unsetenv "PS1"
        --ro-bind "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}"
        --setenv "WAYLAND_DISPLAY" "${WAYLAND_DISPLAY}"
        --ro-bind-try "${XDG_RUNTIME_DIR}/pulse" "${XDG_RUNTIME_DIR}/pulse"
        --ro-bind-try "${HOME}/.config/kdedefaults" "${HOME}/.config/kdedefaults"
        --ro-bind-try "${HOME}/.config/kcminputrc" "${HOME}/.config/kcminputrc"
        --ro-bind-try "${HOME}/.config/kdeglobals" "${HOME}/.config/kdeglobals"
        --ro-bind-try "${HOME}/.config/kwinrc" "${HOME}/.config/kwinrc"
        --ro-bind-try "${HOME}/.config/package" "${HOME}/.config/package"
        --ro-bind-try "${HOME}/.config/plasma-localerc" "${HOME}/.config/plasma-localerc"
        --ro-bind-try "${HOME}/.gtkrc-2.0" "${HOME}/.gtkrc-2.0"
        --ro-bind-try "${HOME}/.config/dconf" "${HOME}/.config/dconf"
        --ro-bind-try "${HOME}/.config/gtkrc" "${HOME}/.config/gtkrc"
        --ro-bind-try "${HOME}/.config/gtkrc-2.0" "${HOME}/.config/gtkrc-2.0"
        --ro-bind-try "${HOME}/.config/gtkrc-3.0/assets" "${HOME}/.config/gtkrc-3.0/assets" 
        --ro-bind-try "${HOME}/.config/gtkrc-3.0/color.css" "${HOME}/.config/gtkrc-3.0/color.css" 
        --ro-bind-try "${HOME}/.config/gtkrc-3.0/gtk.css" "${HOME}/.config/gtkrc-3.0/gtk.css" 
        --ro-bind-try "${HOME}/.config/gtkrc-3.0/settings.ini" "${HOME}/.config/gtkrc-3.0/settings.ini" 
        --ro-bind-try "${HOME}/.config/gtkrc-3.0/window_decorations.css" "${HOME}/.config/gtkrc-3.0/window_decorations.css"
        --ro-bind-try "${HOME}/.config/gtkrc-4.0/assets" "${HOME}/.config/gtkrc-4.0/assets"
        --ro-bind-try "${HOME}/.config/gtkrc-4.0/color.css" "${HOME}/.config/gtkrc-4.0/color.css"
        --ro-bind-try "${HOME}/.config/gtkrc-4.0/gtk.css" "${HOME}/.config/gtkrc-4.0/gtk.css"
        --ro-bind-try "${HOME}/.config/gtkrc-4.0/settings.ini" "${HOME}/.config/gtkrc-4.0/settings.ini"
        --ro-bind-try "${HOME}/.config/gtkrc-4.0/window_decorations.css" "${HOME}/.config/gtkrc-4.0/window_decorations.css"
        --ro-bind-try "${HOME}/.config/user-dirs.locale" "${HOME}/.config/user-dirs.locale"
        --ro-bind-try "${HOME}/.config/user-dirs.dirs" "${HOME}/.config/user-dirs.dirs"
        "${_ga_bwrapsh_dbusproxy[@]}"
        "${_ga_bwrapsh_network[@]}"
        "${_ga_arg1_bwrapsh[@]}"
        --remount-ro "/"
        "${_gs_init_exec}"
        "${_ga_arg2_bwrapsh[@]}"
        "${@}"
)


## execute
"${_ga_exec_bwrapsh[@]}"



### over
## kill
'/usr/bin/kill' -15 "${_gi_proc_dbusproxy}"

