#!/bin/bash


## name
declare -ga "_ga_arg1_bwrapsh_codium"


## variable
_gs_init_exec="/usr/bin/codium"
_gs_mode_network="true"

_ga_arg1_bwrapsh=(
        --ro-bind-try "/_and/config/vscodium"{,}
        --ro-bind-try "/_and/config/nvim"{,}
        --ro-bind-try "/usr/share/bwrapsh/main/patch/bash" "/_and/config/bash"
        --overlay-src "${HOME}"
        --tmp-overlay "${HOME}"
        --overlay-src "${HOME}/.config/VSCodium/User"
        --overlay-src "/_and/config/vscodium/User"
        --tmp-overlay "${HOME}/.config/VSCodium/User"
        --setenv "ELECTRON_OZONE_PLATFORM_HINT" "auto"
        "${_ga_arg1_bwrapsh_codium[@]}"
)

_ga_arg3_bwrapsh=(
        --verbose
        --enable-wayland-ime
        --enable-features=WebRTCPipeWireCapturer
)

