#!/bin/bash


## name
declare -ga "_ga_arg1_bwrapsh_codium"


## variable
_gs_init_exec="/usr/bin/codium"
_gs_mode_network="true"

_ga_arg1_bwrapsh=(
        --overlay-src "/usr/share/bwrapsh/main/patch/bash"
        --tmp-overlay "${HOME}"
        --overlay-src "${HOME}/.pki"
        --tmp-overlay "${HOME}/.pki"
        --overlay-src "${HOME}/.vscode-oss"
        --tmp-overlay "${HOME}/.vscode-oss"
        --overlay-src "${HOME}/.config/VSCodium"
        --tmp-overlay "${HOME}/.config/VSCodium"
        --overlay-src "${HOME}/.config/VSCodium/User"
        --overlay-src "/_and/config/vscodium/User"
        --tmp-overlay "${HOME}/.config/VSCodium/User"
        --overlay-src "/_and/config/nvim"
        --tmp-overlay "/_and/config/nvim"
        --symlink "/_and/config/nvim" "${HOME}/.config/nvim"
        --setenv "ELECTRON_OZONE_PLATFORM_HINT" "auto"
        "${_ga_arg1_bwrapsh_codium[@]}"
)

_ga_arg3_bwrapsh=(
        --verbose
        --enable-wayland-ime
        --enable-features=WebRTCPipeWireCapturer
)

