#!/bin/bash


## function
function _ef_load_init () 
{
        ## name
        declare -g "_gs_fork_home" ;
        ## variable
        _gs_init_name="clash-nyanpasu" ;
        _gs_init_exec="/usr/bin/clash-nyanpasu" ;
        _gs_load_testnet="yes" ;
        _gs_fork_home="/_end/${USER}/_0_data/bwrapsh/home/clash-nyanpasu" ;
        #       #
        _ga_arg1_bwrapsh=(
                --unsetenv "GTK_IM_MODULE"
                --unsetenv "QT_IM_MODULE"
                --unsetenv "SDL_IM_MODULE"
                --bind "${_gs_fork_home}" "${HOME}"
                --tmpfs "${HOME}/.cache"
                --bind "${XDG_RUNTIME_DIR}/tao" "${XDG_RUNTIME_DIR}/tao"
                --setenv "WEBKIT_DISABLE_DMABUF_RENDERER" "1"
        )
}
#       #
declare -fx "_ef_load_init"

function _ef_load_bwrapsh () 
{
        ## command
        if [[ -z "${_gs_fork_home}" ]] ; then
                exit "1" ;
        else
                '/usr/bin/mkdir' -pv "${_gs_fork_home}" ;
        fi
        #       #
        if [[ -z "${XDG_RUNTIME_DIR}" ]] ; then
                exit "1" ;
        else
                '/usr/bin/rm' -rfv "${XDG_RUNTIME_DIR}/tao" ;
                '/usr/bin/mkdir' -pv "${XDG_RUNTIME_DIR}/tao" ;
        fi
}
#       #
declare -fx "_ef_load_bwrapsh"


## execute
'/_and/config/bwrapsh/default/bwrapsh_dbusproxy' "${@}"

