#!/bin/bash


## variable
declare -x "_gs_init_name"
#       #
_gs_init_name="flclash"


## function
function _ef_load_init () 
{
        ## variable
        _gs_init_exec="/usr/bin/FlClash" ;
        _gs_part_home="true" ;
        _gs_part_network="true" ;
        #       #
        _ga_arg1_dbusproxy=(
                --own="com.follow.clash"
        )
        #       #
        _ga_arg1_bwrapsh=(
                --unsetenv "GTK_IM_MODULE"
                --unsetenv "QT_IM_MODULE"
                --unsetenv "SDL_IM_MODULE"
        )
}
declare -fx "_ef_load_init"


## execute
'/_and/config/bwrapsh/default/bwrapsh_dbusproxy' "${@}"

